# cloudbuild.yaml
substitutions:
  _SERVICE_NAME: "hello-world"        # name of your Cloud Run service
  _REGION: "us-central1"             # Cloud Run region
  _REPO: "for-cicd"                   # Artifact Registry repo name (Docker format)

steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    [
      "build",
      "-t",
      "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$COMMIT_SHA",
      "."
    ]

# 2. Push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    [
      "push",
      "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$COMMIT_SHA"
    ]

# 3. Deploy image to Cloud Run
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  id: Deploy
  entrypoint: bash
  args:
    - "-c"
    - |
      gcloud run deploy ${_SERVICE_NAME} \
        --image ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$COMMIT_SHA \
        --region ${_REGION} \
        --platform managed \
        --allow-unauthenticated

# 4. (Optional) Declare built image artifact for tracking
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$COMMIT_SHA"
